#!/usr/bin/env python3
"""Cerebro-derived hostile composition attacks against frozen OpenCore Mini M1-M6.

Attack A — acquisition-aperture self-certification (M2 x M4)
  M4's closure bound assumes a declared challenge protocol.  An active selector
  changes which contexts are sampled, then a naive closure layer counts the
  selected clean reports as though they were generated by the original protocol.

Attack B — prospective policy repair without descendant reconciliation (M6 x lineage)
  M6 changes K_closure after a policy-level failure, but asks only about future
  scopes.  This attack creates sibling legacy closures produced by the same bad
  policy and asks whether changing K_closure also revisits their authority.

mini.py is imported unchanged.  This is a crank-science assay, not a kernel claim.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import math
import random
from dataclasses import dataclass
from pathlib import Path

from mini import MOD, Rule, choose_rules
from mini_004_budgeted_closure import MINI_EXPECTED_SHA256, required_challenges, make_triad
from mini_006_recursive_closure_grounding import (
    ClosurePolicy,
    PolicyEvent,
    ScopeContext,
    respond,
    future_sparse_trial,
)


def mini_sha256() -> str:
    return hashlib.sha256(Path(__file__).with_name("mini.py").read_bytes()).hexdigest()


# ---------------------------------------------------------------------------
# Attack A: acquisition aperture changes the challenge distribution.
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class ApertureWorld:
    rule: Rule
    repeats: int
    x_by_slot: tuple[int, ...]
    defect_slots: frozenset[int]
    selected_xs: frozenset[int]
    defect_xs: frozenset[int]

    @property
    def n(self) -> int:
        return len(self.x_by_slot)

    @property
    def prevalence(self) -> float:
        return len(self.defect_slots) / self.n

    def observe(self, slot: int) -> tuple[int, int, bool]:
        x = self.x_by_slot[slot]
        y = self.rule(x)
        bad = slot in self.defect_slots
        if bad:
            y = (y + 1) % MOD
        return x, y, bad


def _ranking(seed: int) -> list[int]:
    # Public/visible deterministic acquisition preference.  The selector needs no
    # access to latent defect labels; the hostile environment can nevertheless
    # concentrate defects in the region the policy systematically deprioritizes.
    def key(x: int) -> bytes:
        return hashlib.sha256(f"cerebro-aperture:{seed}:{x}".encode()).digest()
    return sorted(range(MOD), key=key)


def make_aperture_world(seed: int, p_min: float = 0.25, repeats: int = 12) -> ApertureWorld:
    rng = random.Random(seed ^ 0xCE8EB0)
    rule = choose_rules(rng)[0]
    ranking = _ranking(seed)

    # Active selector samples the top 8/11 visible x values.  The adversary puts
    # the material defect in the bottom 3/11.  With repeats=12 and one normal twin
    # preserved per affected x, prevalence = 33/132 = .25 exactly.
    defect_xs = frozenset(ranking[:3])
    selected_xs = frozenset(ranking[3:])
    xs = [x for x in range(MOD) for _ in range(repeats)]
    rng.shuffle(xs)
    x_by_slot = tuple(xs)

    defect_slots: set[int] = set()
    # Leave one normal twin in each defect-x to ensure O(x,context) collides on x.
    for x in defect_xs:
        slots = [i for i, sx in enumerate(x_by_slot) if sx == x]
        rng.shuffle(slots)
        defect_slots.update(slots[:-1])

    world = ApertureWorld(rule, repeats, x_by_slot, frozenset(defect_slots), selected_xs, defect_xs)
    if world.prevalence + 1e-12 < p_min:
        raise AssertionError((world.prevalence, p_min))
    return world


def _uniform_trial(world: ApertureWorld, q: int, seed: int) -> bool:
    rng = random.Random(seed ^ 0xA11CE)
    slots = list(range(world.n))
    rng.shuffle(slots)
    return not any(world.observe(s)[2] for s in slots[:q])  # True => false closure


def _selected_trial(world: ApertureWorld, q: int, seed: int) -> bool:
    # Sampling policy chooses only its preferred aperture. No defect labels used.
    rng = random.Random(seed ^ 0x5E1EC7)
    slots = [i for i, x in enumerate(world.x_by_slot) if x in world.selected_xs]
    rng.shuffle(slots)
    if len(slots) < q:
        raise AssertionError("insufficient selected slots")
    return not any(world.observe(s)[2] for s in slots[:q])


def aperture_attack(n: int, p_min: float, delta: float, start_seed: int = 0) -> dict:
    q = required_challenges(p_min, delta)
    uniform_false = 0
    selected_false = 0
    protocol_aware_stops = 0
    prevalences = []
    for seed in range(start_seed, start_seed + n):
        world = make_aperture_world(seed, p_min=p_min)
        prevalences.append(world.prevalence)
        uniform_false += int(_uniform_trial(world, q, seed))
        selected_false += int(_selected_trial(world, q, seed))
        # Protocol-aware controller sees that the acquisition policy differs from
        # the protocol under which the bound was licensed, so it cannot STOP.
        protocol_aware_stops += 0

    return {
        "n": n,
        "contract": {"p_min": p_min, "delta": delta, "q": q, "licensed_protocol": "uniform_random_without_replacement"},
        "active_selector_protocol": "deterministic_visible-x aperture; samples 8/11 x-values",
        "mean_global_defect_prevalence": sum(prevalences) / len(prevalences),
        "uniform_protocol_false_closure_rate": uniform_false / n,
        "naive_selected_stream_false_closure_rate": selected_false / n,
        "protocol_aware_stop_rate_after_protocol_mismatch": protocol_aware_stops / n,
        "key_failure": "selected clean evidence is not licensed evidence for the original sampling protocol",
    }


# ---------------------------------------------------------------------------
# Attack B: policy repair fails to revisit siblings created by bad policy.
# ---------------------------------------------------------------------------

@dataclass
class LegacyClosure:
    seed: int
    world_kind: str
    action_before_policy_repair: str
    authorized_before: bool
    false_closure_harness_only: bool
    status_after_prospective_only_repair: str
    status_after_reconciliation: str


def legacy_decision(seed: int, kind: str, p_min: float, delta: float) -> tuple[str, bool]:
    # Reuse the actual buggy M6 K0 behavior: uncontracted scopes inherit q and can STOP.
    triad = make_triad(seed, p_min)
    case = triad.sparse if kind == "sparse" else triad.sufficient
    q = required_challenges(p_min, delta)
    for slot in triad.challenge_order[:q]:
        obs = case.observe_slot(slot)
        if obs.y != case.rule(obs.x):
            return "CHALLENGE_HIT", False
    # Any STOP is unauthorized: this scope never had an explicit contract.
    return "STOP", kind == "sparse"


def descendant_attack(n: int, p_min: float, delta: float, start_seed: int = 200000) -> dict:
    # Half sufficient, half sparse legacy scopes, all uncontracted.
    legacy: list[LegacyClosure] = []
    for i, seed in enumerate(range(start_seed, start_seed + n)):
        kind = "sparse" if i % 2 else "sufficient"
        action, false_closure = legacy_decision(seed, kind, p_min, delta)
        legacy.append(LegacyClosure(
            seed=seed,
            world_kind=kind,
            action_before_policy_repair=action,
            authorized_before=False,
            false_closure_harness_only=false_closure and action == "STOP",
            status_after_prospective_only_repair=("CLOSED" if action == "STOP" else "OPEN"),
            # Once K0's scope-inheritance rule is established invalid, every legacy
            # STOP produced solely by that unauthorized inheritance is explicitly
            # reconsidered. History remains; current closure standing contracts.
            status_after_reconciliation=("DEFER_REOPENED" if action == "STOP" else "OPEN"),
        ))

    # Trigger exactly the M6 policy correction.
    k0 = ClosurePolicy(require_explicit_contract=False, revision_count=0)
    event = PolicyEvent(
        "POLICY_LEVEL_SURPRISE",
        ScopeContext("trigger/uncontracted", False, None, None),
        True,
        False,
        "uncontracted scope inherited closure authority",
    )
    k1 = respond("grounded", k0, event).policy_after

    stops = [x for x in legacy if x.action_before_policy_repair == "STOP"]
    stale = [x for x in stops if x.status_after_prospective_only_repair == "CLOSED"]
    stale_false = [x for x in stale if x.false_closure_harness_only]
    reconciled_closed = [x for x in stops if x.status_after_reconciliation == "CLOSED"]

    # Show that K1 fixes future behavior but does not, by itself, mutate old ledger entries.
    future = [future_sparse_trial(k1, start_seed + n + j, p_min, delta) for j in range(1000)]

    return {
        "n_legacy_uncontracted_scopes": n,
        "legacy_mix": "50% sufficient / 50% sparse",
        "policy_before": k0.__dict__,
        "policy_after_m6_event": k1.__dict__,
        "legacy_stop_rate_before_repair": len(stops) / n,
        "legacy_stale_closed_rate_after_prospective_only_repair": len(stale) / n,
        "legacy_stale_false_closure_rate_harness_only": len(stale_false) / n,
        "legacy_closed_rate_after_explicit_reconciliation": len(reconciled_closed) / n,
        "future_uncontracted_defer_rate_under_k1": sum(r["action"] == "DEFER" for r in future) / len(future),
        "key_failure": "future policy correction does not automatically repair authority of earlier descendants produced by the invalid policy",
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--sweep", type=int, default=10000)
    ap.add_argument("--p-min", type=float, default=0.25)
    ap.add_argument("--delta", type=float, default=0.10)
    args = ap.parse_args()

    digest = mini_sha256()
    if digest != MINI_EXPECTED_SHA256:
        raise SystemExit(f"mini.py changed: {digest}")

    out = {
        "mini_sha256": digest,
        "mini_unchanged": True,
        "attack_A_acquisition_aperture": aperture_attack(args.sweep, args.p_min, args.delta),
        "attack_B_descendant_reconciliation": descendant_attack(args.sweep, args.p_min, args.delta),
        "claim_boundary": "external composition attacks only; not M7; no new Mini/OpenCore primitive",
    }
    print(json.dumps(out, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
