#!/usr/bin/env python3
"""ARO-001 v0.1 frozen executable.

Do not edit this file after observing v0.1 results. Any change creates v0.2.
"""

from __future__ import annotations

import json
from itertools import product

import numpy as np

CONTEXTS = ("W1_G", "W1_I", "W2_XOR", "W3_GATE")
FIRST_ACTIONS = ("SELECT_G", "SELECT_I", "COMPOSE_GI", "COMPOSE_GIS", "PROBE_S")
SECOND_ACTIONS = ("SELECT_G", "SELECT_I", "COMPOSE_GI")

COST = {
    "SELECT_G": 1.0,
    "SELECT_I": 1.0,
    "COMPOSE_GI": 1.6,
    "COMPOSE_GIS": 2.3,
    "PROBE_S": 1.0,
}

LAMBDA = 0.15
N_SEEDS = 256
TRAIN_EPISODES = 4000
ALPHA = 0.10
GAMMA = 1.0
EPS_START = 0.20
EPS_END = 0.01
H_RECOVER = 1

ORACLE_FIRST = {
    "W1_G": "SELECT_G",
    "W1_I": "SELECT_I",
    "W2_XOR": "COMPOSE_GI",
    "W3_GATE": "PROBE_S",
}

ONE_SHOT_FIRST = {
    "W1_G": "SELECT_G",
    "W1_I": "SELECT_I",
    "W2_XOR": "COMPOSE_GI",
    "W3_GATE": "COMPOSE_GIS",
}


def target(context: str, g: int, i: int, s: int) -> int:
    if context == "W1_G":
        return g
    if context == "W1_I":
        return i
    if context == "W2_XOR":
        return g ^ i
    if context == "W3_GATE":
        return g if s == 0 else i
    raise ValueError(context)


def bayes_predict(context: str, observed: dict[str, int]) -> int:
    ys = []
    for g, i, s in product((0, 1), repeat=3):
        latent = {"G": g, "I": i, "S": s}
        if all(latent[k] == v for k, v in observed.items()):
            ys.append(target(context, g, i, s))
    if not ys:
        raise RuntimeError("No latent state is consistent with observations")
    ones = sum(ys)
    zeros = len(ys) - ones
    return 1 if ones > zeros else 0


def observe_first(action: str, g: int, i: int, s: int) -> tuple[dict[str, int], bool]:
    if action == "SELECT_G":
        return {"G": g}, True
    if action == "SELECT_I":
        return {"I": i}, True
    if action == "COMPOSE_GI":
        return {"G": g, "I": i}, True
    if action == "COMPOSE_GIS":
        return {"G": g, "I": i, "S": s}, True
    if action == "PROBE_S":
        return {"S": s}, False
    raise ValueError(action)


def observe_second(action: str, observed: dict[str, int], g: int, i: int) -> dict[str, int]:
    out = dict(observed)
    if action == "SELECT_G":
        out["G"] = g
    elif action == "SELECT_I":
        out["I"] = i
    elif action == "COMPOSE_GI":
        out["G"] = g
        out["I"] = i
    else:
        raise ValueError(action)
    return out


def choose_eps_greedy(q: np.ndarray, eps: float, rng: np.random.Generator) -> int:
    if rng.random() < eps:
        return int(rng.integers(len(q)))
    max_q = np.max(q)
    ties = np.flatnonzero(np.isclose(q, max_q))
    return int(rng.choice(ties))


def greedy_index(q: np.ndarray) -> int:
    # Deterministic evaluation tie break.
    return int(np.argmax(q))


def run_episode(
    context_idx: int,
    q1: np.ndarray,
    q2: np.ndarray,
    eps: float,
    rng: np.random.Generator,
    learn: bool,
) -> tuple[float, float, str, str | None]:
    context = CONTEXTS[context_idx]
    g, i, s = [int(x) for x in rng.integers(0, 2, size=3)]

    a1_idx = choose_eps_greedy(q1[context_idx], eps, rng) if learn else greedy_index(q1[context_idx])
    a1 = FIRST_ACTIONS[a1_idx]
    observed, terminal = observe_first(a1, g, i, s)
    total_cost = COST[a1]
    a2 = None
    a2_idx = None

    if not terminal:
        a2_idx = choose_eps_greedy(q2[context_idx, s], eps, rng) if learn else greedy_index(q2[context_idx, s])
        a2 = SECOND_ACTIONS[a2_idx]
        observed = observe_second(a2, observed, g, i)
        total_cost += COST[a2]

    y = target(context, g, i, s)
    pred = bayes_predict(context, observed)
    loss = float(pred != y)
    reward = -(loss + LAMBDA * total_cost)

    if learn:
        if a2_idx is not None:
            q2[context_idx, s, a2_idx] += ALPHA * (reward - q2[context_idx, s, a2_idx])
        q1[context_idx, a1_idx] += ALPHA * (reward - q1[context_idx, a1_idx])

    return loss, total_cost, a1, a2


def train(seed: int) -> tuple[np.ndarray, np.ndarray]:
    rng = np.random.default_rng(seed)
    q1 = np.zeros((len(CONTEXTS), len(FIRST_ACTIONS)), dtype=float)
    q2 = np.zeros((len(CONTEXTS), 2, len(SECOND_ACTIONS)), dtype=float)

    for ep in range(TRAIN_EPISODES):
        frac = ep / max(1, TRAIN_EPISODES - 1)
        eps = EPS_START + frac * (EPS_END - EPS_START)
        context_idx = int(rng.integers(len(CONTEXTS)))
        run_episode(context_idx, q1, q2, eps, rng, learn=True)
    return q1, q2


def execute_greedy(q1: np.ndarray, q2: np.ndarray, context: str, g: int, i: int, s: int) -> tuple[float, float, str, str | None]:
    c = CONTEXTS.index(context)
    a1 = FIRST_ACTIONS[greedy_index(q1[c])]
    observed, terminal = observe_first(a1, g, i, s)
    total_cost = COST[a1]
    a2 = None
    if not terminal:
        a2 = SECOND_ACTIONS[greedy_index(q2[c, s])]
        observed = observe_second(a2, observed, g, i)
        total_cost += COST[a2]
    y = target(context, g, i, s)
    pred = bayes_predict(context, observed)
    return float(pred != y), total_cost, a1, a2


def exact_policy_metrics(q1: np.ndarray, q2: np.ndarray) -> dict[str, float]:
    losses = []
    costs = []
    for context in CONTEXTS:
        for g, i, s in product((0, 1), repeat=3):
            loss, cost, _, _ = execute_greedy(q1, q2, context, g, i, s)
            losses.append(loss)
            costs.append(cost)
    loss = float(np.mean(losses))
    cost = float(np.mean(costs))
    j = loss + LAMBDA * cost
    return {"loss": loss, "cost": cost, "J": j}


def exact_fixed_policy(first_map: dict[str, str], route_oracle: bool = False) -> dict[str, float]:
    losses = []
    costs = []
    for context in CONTEXTS:
        for g, i, s in product((0, 1), repeat=3):
            a1 = first_map[context]
            observed, terminal = observe_first(a1, g, i, s)
            cost = COST[a1]
            if not terminal:
                if not route_oracle:
                    raise RuntimeError("Nonterminal fixed policy requires route_oracle=True")
                a2 = "SELECT_G" if s == 0 else "SELECT_I"
                observed = observe_second(a2, observed, g, i)
                cost += COST[a2]
            pred = bayes_predict(context, observed)
            y = target(context, g, i, s)
            losses.append(float(pred != y))
            costs.append(cost)
    loss = float(np.mean(losses))
    cost = float(np.mean(costs))
    return {"loss": loss, "cost": cost, "J": loss + LAMBDA * cost}


def exact_always(action: str) -> dict[str, float]:
    return exact_fixed_policy({c: action for c in CONTEXTS}, route_oracle=False)


def exact_random_policy() -> dict[str, float]:
    losses = []
    costs = []
    weights = []
    for context in CONTEXTS:
        for g, i, s in product((0, 1), repeat=3):
            for a1 in FIRST_ACTIONS:
                observed, terminal = observe_first(a1, g, i, s)
                if terminal:
                    pred = bayes_predict(context, observed)
                    y = target(context, g, i, s)
                    losses.append(float(pred != y))
                    costs.append(COST[a1])
                    weights.append(1.0 / len(FIRST_ACTIONS))
                else:
                    for a2 in SECOND_ACTIONS:
                        obs2 = observe_second(a2, observed, g, i)
                        pred = bayes_predict(context, obs2)
                        y = target(context, g, i, s)
                        losses.append(float(pred != y))
                        costs.append(COST[a1] + COST[a2])
                        weights.append(1.0 / len(FIRST_ACTIONS) / len(SECOND_ACTIONS))
    # Each context/latent state contributes equal total weight; normalize globally.
    w = np.asarray(weights, dtype=float)
    w /= np.sum(w)
    loss = float(np.dot(w, np.asarray(losses, dtype=float)))
    cost = float(np.dot(w, np.asarray(costs, dtype=float)))
    return {"loss": loss, "cost": cost, "J": loss + LAMBDA * cost}


def empty_information_loss(context: str) -> float:
    losses = []
    for g, i, s in product((0, 1), repeat=3):
        pred = bayes_predict(context, {})
        y = target(context, g, i, s)
        losses.append(float(pred != y))
    return float(np.mean(losses))


def policy_shape(q1: np.ndarray, q2: np.ndarray) -> dict[str, object]:
    first = {c: FIRST_ACTIONS[greedy_index(q1[j])] for j, c in enumerate(CONTEXTS)}
    branches = {
        "W3_GATE_S0": SECOND_ACTIONS[greedy_index(q2[CONTEXTS.index("W3_GATE"), 0])],
        "W3_GATE_S1": SECOND_ACTIONS[greedy_index(q2[CONTEXTS.index("W3_GATE"), 1])],
    }
    return {"first": first, "branches": branches}


def seed_diagnostics(q1: np.ndarray, q2: np.ndarray, oracle_J: float) -> dict[str, float | bool]:
    shape = policy_shape(q1, q2)
    first = shape["first"]
    branches = shape["branches"]
    first_acc = np.mean([first[c] == ORACLE_FIRST[c] for c in CONTEXTS])
    branch_acc = np.mean([
        branches["W3_GATE_S0"] == "SELECT_G",
        branches["W3_GATE_S1"] == "SELECT_I",
    ])
    full_equiv = bool(first_acc == 1.0 and branch_acc == 1.0)
    m = exact_policy_metrics(q1, q2)

    # In ARO-A the changed task descriptor is visible immediately. Recovery within
    # one episode therefore equals the fraction of destination task policies that
    # are already oracle-equivalent under the frozen greedy controller.
    per_context_equiv = []
    for c in CONTEXTS:
        ok = first[c] == ORACLE_FIRST[c]
        if c == "W3_GATE":
            ok = ok and branch_acc == 1.0
        per_context_equiv.append(bool(ok))
    recovery_p = float(np.mean(per_context_equiv))

    return {
        "loss": m["loss"],
        "cost": m["cost"],
        "J": m["J"],
        "regret_J": m["J"] - oracle_J,
        "first_operation_accuracy": float(first_acc),
        "W3_branch_accuracy": float(branch_acc),
        "oracle_equivalent_full_policy": full_equiv,
        "P_Trecover_le_1": recovery_p,
    }


def summarize(values: list[float]) -> dict[str, float]:
    a = np.asarray(values, dtype=float)
    return {
        "mean": float(np.mean(a)),
        "sd": float(np.std(a)),
        "min": float(np.min(a)),
        "p05": float(np.quantile(a, 0.05)),
        "median": float(np.median(a)),
        "p95": float(np.quantile(a, 0.95)),
        "max": float(np.max(a)),
    }


def main() -> None:
    oracle = exact_fixed_policy(ORACLE_FIRST, route_oracle=True)
    one_shot = exact_fixed_policy(ONE_SHOT_FIRST, route_oracle=False)
    baselines = {
        "ORACLE_FULL": oracle,
        "ORACLE_ONESHOT": one_shot,
        "ALWAYS_RICH": exact_always("COMPOSE_GIS"),
        "ALWAYS_G": exact_always("SELECT_G"),
        "RANDOM": exact_random_policy(),
    }

    empty_losses = {c: empty_information_loss(c) for c in CONTEXTS}

    rows = []
    learned_shapes = {}
    for seed in range(N_SEEDS):
        q1, q2 = train(seed)
        d = seed_diagnostics(q1, q2, oracle["J"])
        rows.append(d)
        if seed < 8:
            learned_shapes[str(seed)] = policy_shape(q1, q2)

    full_rate = float(np.mean([r["oracle_equivalent_full_policy"] for r in rows]))
    summary = {
        "status": "RUN_COMPLETE",
        "protocol": "ARO-001_IMPLEMENTATION_FREEZE_V0_1",
        "variant": "ARO-A",
        "constants": {
            "seeds": N_SEEDS,
            "training_episodes_per_seed": TRAIN_EPISODES,
            "lambda": LAMBDA,
            "alpha": ALPHA,
            "gamma": GAMMA,
            "epsilon_start": EPS_START,
            "epsilon_end": EPS_END,
            "H_recover": H_RECOVER,
        },
        "matched_nuisance_gate": {
            "empty_information_loss_by_world": empty_losses,
            "passes_exact_half": all(np.isclose(v, 0.5) for v in empty_losses.values()),
        },
        "baselines": baselines,
        "learned": {
            "oracle_equivalent_full_policy_seed_rate": full_rate,
            "loss": summarize([float(r["loss"]) for r in rows]),
            "cost": summarize([float(r["cost"]) for r in rows]),
            "J": summarize([float(r["J"]) for r in rows]),
            "regret_J": summarize([float(r["regret_J"]) for r in rows]),
            "first_operation_accuracy": summarize([float(r["first_operation_accuracy"]) for r in rows]),
            "W3_branch_accuracy": summarize([float(r["W3_branch_accuracy"]) for r in rows]),
            "P_Trecover_le_1": summarize([float(r["P_Trecover_le_1"]) for r in rows]),
            "sample_policy_shapes_first_8_seeds": learned_shapes,
        },
    }

    success = {
        "S1_full_policy_seed_rate_ge_0_95": full_rate >= 0.95,
        "S2_mean_regret_J_le_0_02": summary["learned"]["regret_J"]["mean"] <= 0.02,
        "S3_mean_loss_le_0_01": summary["learned"]["loss"]["mean"] <= 0.01,
        "S4_mean_cost_le_1_425": summary["learned"]["cost"]["mean"] <= 1.425,
        "S5_mean_W3_branch_accuracy_ge_0_95": summary["learned"]["W3_branch_accuracy"]["mean"] >= 0.95,
        "S6_mean_recovery_probability_ge_0_95": summary["learned"]["P_Trecover_le_1"]["mean"] >= 0.95,
        "S7_matched_nuisance_gate": summary["matched_nuisance_gate"]["passes_exact_half"],
    }
    success["ALL_FROZEN_CRITERIA_PASS"] = all(success.values())
    summary["success_criteria"] = success

    print(json.dumps(summary, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
